
# These will probably need to be used by the rubber module used for the web role (nginx)
appserver_base_port: 8000
appserver_count: "#{RUBBER_ENV == 'production' ? 8 : 2}"

roles:
  app:
    gems: [mongrel, mongrel_cluster]

