passenger_root: "/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini"
passenger_ruby: "#{ruby_path}/bin/ruby"
nginx_log_dir: /mnt/nginx/logs
passenger_listen_port: 7000
passenger_listen_ssl_port: 7001
max_app_connections: 20

use_ssl_key: false
#if you use an ssl key, put your cert and key
# in
# #{Rubber.root}/config/#{rubber_env.domain} .crt and .key
#otherwise defaults to key included with linux


roles:
  passenger_nginx:
    packages: [libcurl4-openssl-dev, libpcre3-dev, nginx-extras, passenger]
