passenger_version: '1:4.0.48-1~`lsb_release -sc`1'
passenger_ruby: "#{ruby_path}/bin/ruby"
nginx_log_dir: /mnt/nginx/logs
passenger_listen_port: 7000
passenger_listen_ssl_port: 7001
max_app_connections: 20

use_ssl_key: false
#if you use an ssl key, put your cert and key
# in
# #{Rubber.root}/config/#{rubber_env.domain} .crt and .key
#otherwise defaults to key included with linux


roles:
  passenger_nginx:
    packages: [libcurl4-openssl-dev, libpcre3-dev, nginx-extras, [passenger, "#{passenger_version}"]
