passenger_version: 3.0.19
nginx_version: 1.2.8
passenger_root: "#{`bash -l -c 'find #{ruby_path} -name passenger-#{passenger_version}'`.strip}"
passenger_ruby: "#{ruby_path}/bin/ruby"
passenger_lib: "#{passenger_root}/ext/nginx"
passenger_listen_port: 7000
passenger_listen_ssl_port: 7001
max_app_connections: 20
nginx_log_dir: /mnt/nginx/logs

use_ssl_key: false
#if you use an ssl key, put your cert and key
# in
# #{Rubber.root}/config/#{rubber_env.domain} .crt and .key
#otherwise defaults to key included with linux


roles:
  passenger_nginx:
    packages: [libcurl4-openssl-dev, libpcre3-dev]
    gems: [[passenger, "#{passenger_version}"]]
