language: ruby
sudo: false
cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - ruby-head
  - jruby-9.1.6.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1.6.0

before_install:
  - gem install bundler

# script: bundle exec rspec spec

notifications:
  irc: "irc.freenode.net#rubber"
