<%
  @path = "#{RUBBER_ROOT}/config/database.yml"
%>

<%= RUBBER_ENV %>:
  adapter: postgresql
  encoding: unicode
  database: <%= rubber_env.db_name %>
  username: <%= rubber_env.db_user %>
  password: <%= rubber_env.db_pass %>
  host: <%= rubber_instances.for_role('db', 'primary' => true).first.full_name %>
  pool: 5
