elasticsearch_version: 1.7.0
elasticsearch_config_dir: "/etc/elasticsearch"
elasticsearch_data_dir: "/mnt/elasticsearch/data"
elasticsearch_work_dir: "/mnt/elasticsearch/work"
elasticsearch_log_dir: "/mnt/elasticsearch/logs"
elasticsearch_pid_dir: "/var/run"
elasticsearch_http_port: 9200
elasticsearch_cluster_name: "elasticsearch_#{Rubber.env}"
elasticsearch_expected_nodes: 1
elasticsearch_recover_after_nodes: 1
elasticsearch_plugins:
  - mobz/elasticsearch-head

roles:
  elasticsearch:
    packages: [openjdk-7-jdk, unzip]

web_tools_proxies:
  elasticsearch:
    role: elasticsearch
    port: "#{elasticsearch_http_port}"
    path: /_plugin/head/
