elasticsearch_version: 1.7.0
elasticsearch_cluster_name: "elasticsearch_production"
elasticsearch_data_dir: "/mnt/elasticsearch/data"
elasticsearch_work_dir: "/mnt/elasticsearch/work"
elasticsearch_log_dir: "/mnt/elasticsearch/logs"
elasticsearch_http_port: 9200

roles:
  elasticsearch:
    packages: [openjdk-7-jdk, unzip]

web_tools_proxies:
  elasticsearch:
    role: elasticsearch
    port: "#{elasticsearch_http_port}"
    path: /_plugin/head/
