elasticsearch_version: 0.90.10
elasticsearch_data_dir: "/mnt/elasticsearch/data"
elasticsearch_work_dir: "/mnt/elasticsearch/work"
elasticsearch_log_dir: "/mnt/elasticsearch/logs"
elasticsearch_http_port: 9200

roles:
  elasticsearch:
    packages: [unzip]
    os_packages:
      '12.04': [openjdk-7-jdk]
      '14.04': [openjdk-7-jdk]
      '16.04': [openjdk-8-jdk]

web_tools_proxies:
  elasticsearch:
    role: elasticsearch
    port: "#{elasticsearch_http_port}"
    path: /_plugin/head/
