# rvm needs some extra packages to compile/install ruby runtimes
# curl is required.
# patch is required (for ree, some ruby head's).
# For JRuby (if you wish to use it) you will need:
#   aptitude install curl sun-java6-bin sun-java6-jre sun-java6-jdk
# For MRI & ree (if you wish to use it) you will need:
#   aptitude install curl bison build-essential zlib1g-dev libssl-dev libreadline5-dev libxml2-dev git-core
# For IronRuby (if you wish to use it) you will need:
#   aptitude install curl mono-2.0-devel

packages: [build-essential, git-core, subversion, curl, autoconf, bison, ruby, zlib1g-dev, libssl-dev, libreadline6-dev, libxml2-dev, libyaml-dev]

# REQUIRED: the version of rvm itself
rvm_version: 1.13.0

# REQUIRED: Set to the rvm version string for the ruby version you wish to use
# Run "rvm list known" to see the list of possible options
rvm_ruby: 1.9.3-p194

# OPTIONAL: Extra args to pass to rvm when installing ruby
# rvm_install_options: "--patch falcon,debug --force-autoconf -j 3"

# REQUIRED: Set to version of RubyGems you want RVM to install. Note that older RVMs do not
# know about newer RubyGems.  So you may need to bump your rvm_version to get the latest RubyGems release.
rubygems_version: 1.8.23

# REQUIRED: Set to version of rake you want RVM to install.
rake_version: 0.9.2.2

# When rvm is installed as root, and you set the default, it symlinks ruby executables
# into /usr/local/rvm
ruby_prefix: /usr/local/rvm

rvm_prefix: /usr/local/rvm
  
# lets us setup global environment to use rvm (also needed when running sudo)
rvm_prepare: "source #{rvm_prefix}/scripts/rvm"

# dirty hack to get the rvm gem home rather than bundler gem home
# When we run rubber:config it loads rails/bundler, which forces the bundler gem home, yet deployment only gems
# like passenger need to be installed in rvm gem home rather than bundler
rvm_gem_home: "#{$rubber_rvm_gem_home ||= `unset GEM_HOME; bash -l -c 'rvm gemdir'`.strip}"
