# OPTIONAL: The dns provider to use.  Need to exist in dns_providers below
# dns_provider: nettica

# OPTIONAL: The configuration for each dns provider (nettica|zerigo|dyndns)
#          This lets rubber update a dynamic dns service with the instance alias and ip
#
dns_providers:
  aws:
    access_key: "#{cloud_providers.aws.access_key}"
    access_secret: "#{cloud_providers.aws.secret_access_key}"
    type: A
    ttl: 300
  nettica:
    user: joe
    password: sekret
    type: A
    ttl: 300
  zerigo:
    email: foo@bar.com
    token: hexxy
    type: A
    ttl: 300
  dyndns:
    user: joe
    password: sekret
    update_url: https://members.dyndns.org/nic/update?hostname=%host%&myip=%ip%'

# OPTIONAL: Lets you configure your dns service, for example to add other CNAMES
#           or setup dns round robin, etc.  Run "cap rubber:setup_dns_records"
#           to apply them as rubber only sets up instance aliases as part of
#           the standard lifecycle
#
#  dns_records:
#    # simple A record
#    - host: bar
#      data: [1.1.1.1]
#
#    # more detailed A record
#    - host: bar
#      domain: otherdomain.com
#      data: [1.1.1.1]
#      type: A
#      ttl: 300
#
#    # tld A record
#    - host: ''
#      data: [1.1.1.1]
#      type: A
#
#    # tld ALIAS record -- Route53 extension to point tld at an Elastic Load Balancer group
#    - host: ''
#      domain: example.com
#      type: A
#      data:
#        - hosted_zone_id: XXYYZZ
#          dns_name: my-app-elb-group.us-east-1.elb.amazonaws.com
#
#    # simple CNAME record
#    - host: otherbar
#      domain: foo.com
#      data: [bar.foo.com]
#      type: CNAME
#      ttl: 300
#
#    # Round robin dns record
#    - host: rr
#      domain: foo.com
#      data: [1.1.1.1, 1.1.1.2]
#      type: A
#      ttl: 300
#
#    # A record, grabbing ip from instance config
#    - host: baz
#      domain: foo.com
#      data: ["#{rubber_instances.for_role('web').first.external_ip}"]
#      type: A
#      ttl: 300
#
#    # MX record
#    - host: ''
#      domain: foo.com
#      data:
#        - priority: 5
#          value: mail1.foo.com
#        - priority: 10
#          value: mail2.foo.com
#      type: MX
#      ttl: 300

